---
pgmo:
  time_horizon: 100.0
  d_graph_resolution: 2.5
  mesh_resolution: 0.005
objects:
  prefix: O
  active_horizon_s: 10.0
  active_index_horizon_m: 7.0
  min_cluster_size: 25
  max_cluster_size: 100000
  cluster_tolerance: 0.18
surface_places:
  type: place_2d
  prefix: P

  # Max side length for places without any other overlappig semantic classes
  pure_final_place_size: 1

  # Whether to further subdivide places that overlap other semantic classes
  enable_place_purity: false
  # Max side length for places with overlapping semantic class
  impure_final_place_size: 1

  # Params related to place clustering
  cluster_tolerance: .3
  min_cluster_size: 50
  max_cluster_size: 100000
  min_final_place_points: 10

  # Params related to place edge connections
  place_max_neighbor_z_diff: 100
  place_overlap_threshold: 0.0

min_object_vertices: 20
prune_mesh_indices: true

enable_active_mesh_pub: false
enable_segmented_mesh_pub: false

freespace_places:
    type: gvd
    filter_places: true
    min_places_component_size: 3

    gvd:
      max_distance_m: 4.5
      min_distance_m: 0.2
      min_diff_m: 0.1
      min_weight: 1.0e-6
      positive_distance_only: true
      min_basis_for_extraction: 1
      num_buckets: 20
      multi_queue: false
      extract_graph: true
      voronoi_config:
        mode: L1_THEN_ANGLE
        min_distance_m: 0.30
        parent_l1_separation: 20
        parent_cos_angle_separation: 0.2

    graph:
      type: CompressionGraphExtractor
      compression_distance_m: 1.0
      validate_graph: false
      min_node_distance_m: 0.4
      min_edge_distance_m: 0.25
      node_merge_distance_m: 0.5
      # heurisitic edges
      add_heuristic_edges: false
      add_overlap_edges: true
      overlap_edges:
        num_neighbors_to_check: 4
        min_clearance_m: 0.4
      add_freespace_edges: false
      freespace_edges:
        num_nodes_to_check: 5
        num_neighbors_to_find: 1
        max_length_m: 2.0
        min_clearance_m: 0.5

use_frontiers: true
frontier_places:
    type: "voxel_clustering"
    cluster_tolerance: 0.3
    min_cluster_size: 10
    max_cluster_size: 100000
    max_place_radius: 5
    dense_frontiers: false
    frontier_splitting_threshold: 0.3
    point_threshold: 10
    culling_point_threshold: 50
    recent_block_distance: 25
