---
pgmo:
  time_horizon: 100.0
  d_graph_resolution: 2.5
  mesh_resolution: 0.005
objects:
  prefix: O
  active_horizon_s: 10.0
  active_index_horizon_m: 7.0
  min_cluster_size: 25
  max_cluster_size: 100000
  cluster_tolerance: 0.18
min_object_vertices: 20
