---
total_semantic_labels: 46
dynamic_labels: [1, 5, 24, 25, 26, 27, 28, 30, 31, 32, 33, 43]
invalid_labels: [0, 1, 2, 3, 4, 5, 23, 45]
object_labels: [17, 19, 20, 26, 27, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40, 41]
surface_places_labels: [6, 7, 8, 9, 10, 15, 21, 22]
label_names:
  - {label: 0, name: unlabeled, name_descriptive: unknown}
  - {label: 1, name: ego_vehicle, name_descriptive: an ego vehicle}
  - {label: 2, name: rectification, name_descriptive: a rectification border}
  - {label: 3, name: out, name_descriptive: out of region of interest}
  - {label: 4, name: static, name_descriptive: a static object}
  - {label: 5, name: dynamic, name_descriptive: a dynamic object}
  - {label: 6, name: ground, name_descriptive: the ground}
  - {label: 7, name: road, name_descriptive: a part of a road}
  - {label: 8, name: sidewalk, name_descriptive: a sidewalk}
  - {label: 9, name: parking, name_descriptive: a parking space}
  - {label: 10, name: rail, name_descriptive: a railroad track}
  - {label: 11, name: building, name_descriptive: a building}
  - {label: 12, name: wall, name_descriptive: a wall}
  - {label: 13, name: fence, name_descriptive: a fence}
  - {label: 14, name: guard, name_descriptive: a guard rail}
  - {label: 15, name: bridge, name_descriptive: a bridge}
  - {label: 16, name: tunnel, name_descriptive: a tunnel}
  - {label: 17, name: pole, name_descriptive: a pole}
  - {label: 18, name: pole_group, name_descriptive: a group of poles}
  - {label: 19, name: traffic_light, name_descriptive: a traffic light}
  - {label: 20, name: traffic_sign, name_descriptive: a traffic sign}
  - {label: 21, name: vegetation, name_descriptive: vegetation}
  - {label: 22, name: terrain, name_descriptive: terrain}
  - {label: 23, name: sky, name_descriptive: the sky}
  - {label: 24, name: person, name_descriptive: a person}
  - {label: 25, name: rider, name_descriptive: a rider}
  - {label: 26, name: car, name_descriptive: a car}
  - {label: 27, name: truck, name_descriptive: a truck}
  - {label: 28, name: bus, name_descriptive: a bus}
  - {label: 29, name: caravan, name_descriptive: a caravan}
  - {label: 30, name: trailer, name_descriptive: a trailer}
  - {label: 31, name: train, name_descriptive: a train}
  - {label: 32, name: motorcycle, name_descriptive: a motorcycle}
  - {label: 33, name: bicycle, name_descriptive: a bicycle}
  - {label: 34, name: garage, name_descriptive: a garage}
  - {label: 35, name: gate, name_descriptive: a gate}
  - {label: 36, name: stop, name_descriptive: a stop}
  - {label: 37, name: small_pole, name_descriptive: a small pole}
  - {label: 38, name: lamp, name_descriptive: a lamp}
  - {label: 39, name: trash, name_descriptive: a trash can}
  - {label: 40, name: vending, name_descriptive: a vending machine}
  - {label: 41, name: box, name_descriptive: a box}
  - {label: 42, name: construction, name_descriptive: construction}
  - {label: 43, name: vehicle, name_descriptive: an unknown vehicle}
  - {label: 44, name: object, name_descriptive: an unknown object}
  - {label: 45, name: license, name_descriptive: a license plate}
