---
total_semantic_labels: 24
dynamic_labels: [16]
invalid_labels: []
obejct_labels: [3, 4, 7, 8, 14, 15, 18, 19, 20, 23]
surface_places_labels: [0, 1, 2, 5, 9, 10, 12, 13, 21, 22]
label_names:
  - {label: 0, name: dirt}
  - {label: 1, name: sand}
  - {label: 2, name: grass}
  - {label: 3, name: tree}
  - {label: 4, name: pole}
  - {label: 5, name: water}
  - {label: 6, name: sky}
  - {label: 7, name: vehicle}
  - {label: 8, name: container}
  - {label: 9, name: asphalt}
  - {label: 10, name: gravel}
  - {label: 11, name: building}
  - {label: 12, name: mulch}
  - {label: 13, name: rock-bed}
  - {label: 14, name: log}
  - {label: 15, name: bicycle}
  - {label: 16, name: person}
  - {label: 17, name: fence}
  - {label: 18, name: bush}
  - {label: 19, name: sign}
  - {label: 20, name: rock}
  - {label: 21, name: bridge}
  - {label: 22, name: concrete}
  - {label: 23, name: picnic-table}
