---
total_semantic_labels: 21
dynamic_labels: [20]
invalid_labels: []
object_labels: [5, 7, 8, 10, 18]
label_names:
  - {label: 0, name: unknown}
  - {label: 1, name: vending_machine}
  - {label: 3, name: floor}
  - {label: 4, name: ceiling}
  - {label: 6, name: unknown}
  - {label: 7, name: bench}
  - {label: 8, name: train}
  - {label: 10, name: phone}
  - {label: 11, name: lamp}
  - {label: 14, name: sign}
  - {label: 15, name: stairs}
  - {label: 18, name: trashcan}
  - {label: 19, name: wall}
  - {label: 20, name: human}
