services:
  hydra-ws-build:
    build: 
      context: .
      dockerfile: Dockerfile
    # TODO: Specify the target platform to build the image, otherwise it will build for the host platform.
    # Reference: https://docs.docker.com/compose/compose-file/build/#platforms
    # platforms:
    #   - "linux/arm64"
    image: assume/ros1-hydra-ws
    container_name: ros1-hydra-ws-build
    stdin_open: true
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    command: /bin/bash -c "cd /home/user/catkin_ws && sudo apt update && ./install.sh"
    network_mode: host
    working_dir: /home/user
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_WS=/home/user/catkin_ws
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Mount device
      - /dev:/dev
      # Mount github ssh key
      - ~/.ssh:/home/user/.ssh
      # Mount workspace
      - ..:/home/user/catkin_ws/

  hydra-ws:
    build: 
      context: .
      dockerfile: Dockerfile
    # TODO: Specify the target platform to build the image, otherwise it will build for the host platform.
    # Reference: https://docs.docker.com/compose/compose-file/build/#platforms
    # platforms:
    #   - "linux/arm64"
    image: assume/ros1-hydra-ws
    container_name: ros1-hydra-ws
    stdin_open: true
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    command: /bin/bash
    network_mode: host
    working_dir: /home/user
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_WS=/home/user/catkin_ws
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Mount device
      - /dev:/dev
      # Mount github ssh key
      - ~/.ssh:/home/user/.ssh
      # Mount workspace
      - ..:/home/user/catkin_ws/