---
type: RosInput
tf_verbosity: 1
clear_queue_on_fail: true
receivers:
  - type: ImageReceiver
    sensor:
      type: camera_info
      min_range: $(arg sensor_min_range)
      max_range: $(arg sensor_max_range)
      camera_info_topic: $(arg rgb_info_topic)
      extrinsics:
        type: ros
        sensor_frame: $(arg sensor_frame)
