# model_filename: "/home/user/catkin_ws/src/segmentation/scripts/lseg_minimal/checkpoints/lseg_minimal_e200.ckpt"

visualization: False
output_csv: True
output_label_space: True
label_class: "floor,wall,ceiling,door,sofa,table,chair,bicycle,other"