---
pgmo:
  time_horizon: 15.0
  d_graph_resolution: 2.5
  mesh_resolution: 0.005
objects:
  prefix: O
  active_index_horizon_m: 7.0
  min_cluster_size: 40
  max_cluster_size: 100000
  cluster_tolerance: 0.25
min_object_vertices: 40
freespace_places:
  type: gvd
  gvd:
    max_distance_m: 4.5
    min_distance_m: 0.2
    min_diff_m: 0.1
    min_weight: 1.0e-6
    positive_distance_only: true
    min_basis_for_extraction: 1
    num_buckets: 20
    multi_queue: false
    extract_graph: true
    voronoi_config:
      mode: L1_THEN_ANGLE
      min_distance_m: 0.30
      parent_l1_separation: 20
      parent_cos_angle_separation: 0.2
  graph:
    type: CompressionGraphExtractor
    compression_distance_m: 1.0
    validate_graph: false
    min_node_distance_m: 0.4
    min_edge_distance_m: 0.2
    node_merge_distance_m: 0.5
      # heurisitic edges
    add_heuristic_edges: true
    add_overlap_edges: false
    overlap_edges:
      num_neighbors_to_check: 4
      min_clearance_m: 0.4
    add_freespace_edges: true
    freespace_edges:
      num_nodes_to_check: 10
      num_neighbors_to_find: 2
      max_length_m: 2.0
      min_clearance_m: 0.2
  tsdf_interpolator:
    type: downsample
    ratio: 2
